# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SpotifySignInExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifySignInExample
    pod 'Alamofire', '~> 5.0'
    

  workspace 'SpotifySignInExample'
end
